server:
  port: 80

spring:
    thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      cache: false

tcp:
  port: 8090
  ip: 127.0.0.1
